version: "2"

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=6jhVPaQWhgEMl0sXPnNmkLfS
      - POSTGRES_ROOT_PASSWORD=qgZqZGdoe5loJ0OrZvq36LBr
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_LOGLEVEL=WARNING
      - DB_VENDOR=postgres
      - DB_USER=keycloak
      - DB_DATABASE=keycloak
      - DB_PASSWORD=6jhVPaQWhgEMl0sXPnNmkLfS
      - DB_PORT=5432
      - DB_ADDR=db
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=P@ss4dmin
      - KEYCLOAK_STATISTICS=all
    links:
      - db:postgres
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
    driver: local
